import{S as p,i}from"./assets/vendor-BrddEoy-.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const g="46071248-68730f1ac11d3747a84542f11",y="https://pixabay.com/api/";async function h(t,o=1,n=12){const s=`${y}?key=${g}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=${n}`;try{const e=await fetch(s);if(!e.ok)throw new Error("HTTP error");return(await e.json()).hits}catch(e){throw console.error("Error fetching images:",e),e}}function b(t,o){const n=t.map(({webformatURL:s,largeImageURL:e,tags:r,likes:a,views:f,comments:d,downloads:m})=>`
            <a href="${e}" class="gallery__item">
                <img src="${s}" alt="${r}" loading="lazy" />
                <div class="info">
                    <p><b>Likes</b> ${a}</p>
                    <p><b>Views</b> ${f}</p>
                    <p><b>Comments</b> ${d}</p>
                    <p><b>Downloads</b> ${m}</p>
                </div>
            </a>
        `).join("");o.innerHTML=n}function L(t){t.innerHTML=""}const w=document.querySelector("#search-form"),c=document.querySelector(".gallery"),l=document.querySelector(".loader");let $=new p(".gallery a"),S=1;w.addEventListener("submit",async t=>{t.preventDefault();const o=t.currentTarget.elements.searchQuery.value.trim();if(!o){i.error({title:"Error",message:"Search query cannot be empty!"});return}L(c),u(!0);try{const n=await h(o,S);n.length===0?i.info({title:"Sorry",message:"There are no images matching your search query. Please try again!"}):(b(n,c),$.refresh())}catch{i.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{u(!1)}});function u(t){t?l.classList.remove("hidden"):l.classList.add("hidden")}
//# sourceMappingURL=index.js.map
